backend:
  name: git-gateway

media_folder: "static/uploads"
public_folder: "/uploads"

locale: 'fr'

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Images", name: "thumbnail", widget: "image"}
      - {label: "Date de publication", name: "date", widget: "date"}
      - {label: "Ordre", name: "order", widget: "number", valueType: "int", min: 1, step: 1}
      - {label: "Contenu", name: "body", widget: "markdown"}